#!/bin/bash

stow fish
stow starship
stow vim
stow neovim
stow spacemacs
stow emacs
stow tmux
stow tig
stow kitty
if [ "$(uname)" == "Darwin" ]; then
  stow vscode@macOS
fi
if [ "$(uname)" == "Linux" ]; then
  stow vscode@linux
fi
#stow git
