add_newline = false
prompt_order = [
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "package",
    "line_break",
    "jobs",
    "character"
]

[character]
symbol = "➜"

[line_break]
disabled = true

[git_branch]
style = "yellow"
