add_newline = false
format = """\
    $username\
    $hostname\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $line_break\
    $character\
"""

[character]
success_symbol = "➜"

[line_break]
disabled = true

[git_branch]
style = "yellow"
symbol = ""
